const houses =[
    {
        number: 1,
        posX: 11,
        posY: 18,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 2,
        posX: 12,
        posY: 25,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 3,
        posX: 22,
        posY: 17,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 4,
        posX: 31,
        posY: 16,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 5,
        posX: 41,
        posY: 14,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 6,
        posX: 52,
        posY: 12,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 7,
        posX: 73,
        posY: 7,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 8,
        posX: 17,
        posY: 31,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 9,
        posX: 24,
        posY: 28,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 10,
        posX: 33,
        posY: 28,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 11,
        posX: 41,
        posY: 28,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 12,
        posX: 52,
        posY: 26,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 13,
        posX: 77,
        posY: 17,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 14,
        posX: 73,
        posY: 27,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 15,
        posX: 22,
        posY: 37,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 16,
        posX: 34,
        posY: 37,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 17,
        posX: 44,
        posY: 36,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 18,
        posX: 55,
        posY: 35,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 19,
        posX: 79,
        posY: 35,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 20,
        posX: 21,
        posY: 45,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 21,
        posX: 26,
        posY: 50,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 22,
        posX: 33,
        posY: 50,
        isBuy: true,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 23,
        posX: 42,
        posY: 49,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 24,
        posX: 54,
        posY: 49,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 25,
        posX: 74,
        posY: 45,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 26,
        posX: 74,
        posY: 52,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 27,
        posX: 37,
        posY: 63,
        isBuy: true,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 28,
        posX: 53,
        posY: 62,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 29,
        posX: 75,
        posY: 63,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 30,
        posX: 75,
        posY: 71,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 31,
        posX: 42,
        posY: 73,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 32,
        posX: 52,
        posY: 74,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 33,
        posX: 52,
        posY: 82,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 34,
        posX: 75,
        posY: 81,
        isBuy: true,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },
    {
        number: 35,
        posX: 75,
        posY: 89,
        isBuy: false,
        price: 500,
        square: 700,
        totalSquare: 1200,
    },

]